import { Feather } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { reports } from '@/data/mockData';
import { colors, fonts } from '@/theme';
import { SectionHeading } from './SectionHeading';
import { TopographicLines } from './TopographicLines';

export function CommunitySection({ compact }: { compact: boolean }) {
 const [likedReports, setLikedReports] = useState<string[]>([]);
 const [communityMessage, setCommunityMessage] = useState('');
 const toggleLiked = (author: string) => setLikedReports((current) => current.includes(author) ? current.filter((item) => item !== author) : [...current, author]);
 return <View style={styles.section}><TopographicLines light /><View style={styles.inner}><View style={[styles.top, compact && styles.topMobile]}><SectionHeading light eyebrow="From the lift line" title={'The mountain is\ntalking.'} copy="Sample reports from a prototype ski day. These posts and conditions are not live." /><View style={styles.live}><View style={styles.pulse} /><Text style={styles.liveText}>SAMPLE MOUNTAIN REPORTS</Text></View></View><View style={[styles.feed, compact && styles.feedMobile]}>{reports.map((r, i) => { const liked = likedReports.includes(r.author); return <View key={r.author} style={[styles.report, i === 1 && styles.reportTilt]}><View style={styles.reportTop}><View style={[styles.avatar, { backgroundColor: r.accent }]}><Text style={styles.initials}>{r.initials}</Text></View><View style={styles.author}><Text style={styles.authorName}>{r.author}</Text><Text style={styles.place}>{r.mountain}  ·  SAMPLE POST</Text></View><Text style={styles.snow}>✳</Text></View><Text style={styles.reportText}>“{r.text}”</Text><View style={styles.reportBottom}><Text style={styles.condition}>●  SAMPLE · NOT LIVE</Text><Pressable accessibilityRole="button" accessibilityLabel={`${liked ? 'Unlike' : 'Like'} ${r.author}'s sample report`} accessibilityState={{ selected: liked }} onPress={() => toggleLiked(r.author)} style={[styles.like, liked && styles.likeActive]}><Feather name={liked ? 'check' : 'heart'} size={18} color={colors.forest} /></Pressable></View></View>; })}</View><Pressable accessibilityRole="button" onPress={() => setCommunityMessage('Community profiles and live posting are coming soon.')} style={styles.join}><Text style={styles.joinText}>SEE WHAT&apos;S HAPPENING</Text><Feather name="arrow-right" size={17} color={colors.deep} /></Pressable>{communityMessage ? <Text accessibilityLiveRegion="polite" style={styles.joinMessage}>{communityMessage}</Text> : null}</View></View>;
}
const styles = StyleSheet.create({ section: { backgroundColor: colors.deep, paddingVertical: 105, overflow: 'hidden' }, inner: { maxWidth: 1160, width: '100%', alignSelf: 'center', paddingHorizontal: 24 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 52 }, topMobile: { flexDirection: 'column', alignItems: 'flex-start', gap: 25 }, live: { flexDirection: 'row', gap: 9, alignItems: 'center', borderColor: '#49665f', borderWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, pulse: { width: 8, height: 8, borderRadius: 5, backgroundColor: colors.orange }, liveText: { color: colors.white, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.3 }, feed: { flexDirection: 'row', gap: 20 }, feedMobile: { flexDirection: 'column' }, report: { flex: 1, backgroundColor: colors.paper, padding: 24, minHeight: 230, transform: [{ rotate: '-.7deg' }] }, reportTilt: { transform: [{ translateY: 16 }, { rotate: '1deg' }] }, reportTop: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.deep, fontFamily: fonts.bold, fontSize: 11 }, author: { flex: 1, marginLeft: 10 }, authorName: { color: colors.forest, fontFamily: fonts.bold, fontSize: 13 }, place: { color: colors.muted, fontFamily: fonts.body, fontSize: 9, marginTop: 2 }, snow: { color: colors.orange, fontSize: 20 }, reportText: { color: colors.forest, fontFamily: fonts.display, fontSize: 19, lineHeight: 27, marginTop: 25, flex: 1 }, reportBottom: { borderTopColor: '#ddd6c9', borderTopWidth: 1, paddingTop: 10, marginTop: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, condition: { color: '#597467', fontFamily: fonts.bold, fontSize: 8, letterSpacing: 1 }, like: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderColor: 'transparent', borderWidth: 1 }, likeActive: { backgroundColor: colors.lime, borderColor: colors.forest }, join: { alignSelf: 'center', minHeight: 48, backgroundColor: colors.lime, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 55, transform: [{ rotate: '-1deg' }] }, joinText: { color: colors.deep, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.2 }, joinMessage: { color: '#c8d6d1', fontFamily: fonts.body, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 14 } });
