import { Feather } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { reports } from '@/data/mockData';
import { colors, fonts } from '@/theme';
import { SectionHeading } from './SectionHeading';
import { TopographicLines } from './TopographicLines';

export function CommunitySection({ compact }: { compact: boolean }) {
 return <View style={styles.section}><TopographicLines light /><View style={styles.inner}><View style={[styles.top, compact && styles.topMobile]}><SectionHeading light eyebrow="From the lift line" title={'The mountain is\ntalking.'} copy="Fresh reports from people who are actually out there. No stale forecasts. No fluff." /><View style={styles.live}><View style={styles.pulse} /><Text style={styles.liveText}>LIVE MOUNTAIN REPORT</Text></View></View><View style={[styles.feed, compact && styles.feedMobile]}>{reports.map((r, i) => <View key={r.author} style={[styles.report, i === 1 && styles.reportTilt]}><View style={styles.reportTop}><View style={[styles.avatar, { backgroundColor: r.accent }]}><Text style={styles.initials}>{r.initials}</Text></View><View style={styles.author}><Text style={styles.authorName}>{r.author}</Text><Text style={styles.place}>{r.mountain}  ·  {r.time}</Text></View><Text style={styles.snow}>✳</Text></View><Text style={styles.reportText}>“{r.text}”</Text><View style={styles.reportBottom}><Text style={styles.condition}>●  ON MOUNTAIN</Text><Pressable><Feather name="heart" size={18} color={colors.forest} /></Pressable></View></View>)}</View><Pressable style={styles.join}><Text style={styles.joinText}>SEE WHAT&apos;S HAPPENING</Text><Feather name="arrow-right" size={17} color={colors.deep} /></Pressable></View></View>;
}
const styles = StyleSheet.create({ section: { backgroundColor: colors.deep, paddingVertical: 105, overflow: 'hidden' }, inner: { maxWidth: 1160, width: '100%', alignSelf: 'center', paddingHorizontal: 24 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 52 }, topMobile: { flexDirection: 'column', alignItems: 'flex-start', gap: 25 }, live: { flexDirection: 'row', gap: 9, alignItems: 'center', borderColor: '#49665f', borderWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, pulse: { width: 8, height: 8, borderRadius: 5, backgroundColor: colors.lime }, liveText: { color: colors.white, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.3 }, feed: { flexDirection: 'row', gap: 20 }, feedMobile: { flexDirection: 'column' }, report: { flex: 1, backgroundColor: colors.paper, padding: 24, minHeight: 230, transform: [{ rotate: '-.7deg' }] }, reportTilt: { transform: [{ translateY: 16 }, { rotate: '1deg' }] }, reportTop: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.deep, fontFamily: fonts.bold, fontSize: 11 }, author: { flex: 1, marginLeft: 10 }, authorName: { color: colors.forest, fontFamily: fonts.bold, fontSize: 13 }, place: { color: colors.muted, fontFamily: fonts.body, fontSize: 9, marginTop: 2 }, snow: { color: colors.orange, fontSize: 20 }, reportText: { color: colors.forest, fontFamily: fonts.display, fontSize: 19, lineHeight: 27, marginTop: 25, flex: 1 }, reportBottom: { borderTopColor: '#ddd6c9', borderTopWidth: 1, paddingTop: 14, marginTop: 18, flexDirection: 'row', justifyContent: 'space-between' }, condition: { color: '#597467', fontFamily: fonts.bold, fontSize: 8, letterSpacing: 1 }, join: { alignSelf: 'center', backgroundColor: colors.lime, paddingHorizontal: 22, paddingVertical: 15, flexDirection: 'row', gap: 10, marginTop: 55, transform: [{ rotate: '-1deg' }] }, joinText: { color: colors.deep, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.2 } });
