import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { resorts } from '@/data/mockData';
import { colors, fonts } from '@/theme';
import { SectionHeading } from './SectionHeading';

export function ResortSection({ compact }: { compact: boolean }) {
 const router = useRouter();
 const routes = ['/resorts/heavenly', '/resorts/palisades-tahoe', '/resorts/mammoth-mountain'] as const;
 return <View style={styles.section}><View style={styles.inner}><View style={[styles.headingRow, compact && styles.headingMobile]}><SectionHeading eyebrow="Pick your playground" title="Mountains worth waking up early for." copy="Trail beta, conditions, and local energy — all in one place." /><Pressable style={styles.all}><Text style={styles.allText}>EXPLORE ALL RESORTS</Text><Feather name="arrow-right" size={15} color={colors.forest} /></Pressable></View>
  <View style={[styles.grid, compact && styles.gridMobile]}>{resorts.map((r, i) => <Pressable accessibilityRole="link" onPress={() => router.push(routes[i])} key={r.name} style={({ hovered }: any) => [styles.card, i === 1 && styles.offset, compact && styles.noOffset, hovered && styles.cardHover]}><View style={[styles.tape, { backgroundColor: i === 1 ? '#efab83' : '#e9dfba' }]} /><ImageBackground source={{ uri: r.image }} style={[styles.image, { backgroundColor: r.color }]} imageStyle={styles.imageStyle}><View style={styles.location}><Text style={styles.locationText}>{r.location.toUpperCase()}</Text></View></ImageBackground><View style={styles.cardBody}><View><Text style={styles.name}>{r.name}</Text><Text style={styles.meta}>{r.vertical} vertical  ·  {r.trails} trails</Text></View><View style={styles.go}><Feather name="arrow-up-right" size={19} color={colors.white} /></View></View></Pressable>)}</View>
 </View></View>;
}
const styles = StyleSheet.create({ section: { backgroundColor: '#e9e1d3', paddingVertical: 105 }, inner: { maxWidth: 1180, width: '100%', alignSelf: 'center', paddingHorizontal: 24 }, headingRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 55 }, headingMobile: { flexDirection: 'column', alignItems: 'flex-start', gap: 25 }, all: { borderBottomColor: colors.forest, borderBottomWidth: 1, paddingBottom: 7, flexDirection: 'row', gap: 8 }, allText: { color: colors.forest, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.2 }, grid: { flexDirection: 'row', gap: 24 }, gridMobile: { flexDirection: 'column', gap: 45 }, card: { flex: 1, backgroundColor: colors.paper, padding: 10, paddingBottom: 0, transform: [{ rotate: '-1deg' }], shadowColor: '#173d33', shadowOpacity: .18, shadowRadius: 13, shadowOffset: { width: 5, height: 9 } }, offset: { transform: [{ translateY: 25 }, { rotate: '1.5deg' }] }, noOffset: { transform: [{ translateY: 0 }, { rotate: '0deg' }] }, cardHover: { transform: [{ translateY: -5 }, { rotate: '.5deg' }] }, tape: { position: 'absolute', zIndex: 2, top: -14, left: '37%', width: 85, height: 28, opacity: .85, transform: [{ rotate: '-4deg' }] }, image: { height: 250, justifyContent: 'flex-start', alignItems: 'flex-start' }, imageStyle: { }, location: { backgroundColor: colors.lime, paddingHorizontal: 10, paddingVertical: 6, margin: 10 }, locationText: { color: colors.deep, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1 }, cardBody: { minHeight: 98, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, name: { color: colors.forest, fontFamily: fonts.display, fontSize: 24 }, meta: { color: colors.muted, fontFamily: fonts.body, fontSize: 11, marginTop: 5 }, go: { backgroundColor: colors.orange, width: 36, height: 36, borderRadius: 19, alignItems: 'center', justifyContent: 'center' } });
