import { Feather } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { vibes } from '@/data/mockData';
import { colors, fonts } from '@/theme';
import { SectionHeading } from './SectionHeading';
import { TopographicLines } from './TopographicLines';

export function VibeSection({ compact }: { compact: boolean }) {
  const [selected, setSelected] = useState('Trees, please');
  return <View style={styles.section}><TopographicLines /><View style={[styles.inner, compact && styles.mobile]}>
    <View style={styles.intro}><View style={styles.number}><Text style={styles.numberText}>01</Text></View><SectionHeading eyebrow="Match your mood" title={'What should I\nski next?'} copy="Tell us what kind of day you're having. We'll point you toward the right side of the mountain." /><View style={styles.arrow}><Text style={styles.arrowText}>↝</Text><Text style={styles.note}>NO ALGORITHM{`\n`}CAN FEEL YOUR LEGS</Text></View></View>
    <View style={styles.panel}><Text style={styles.panelEyebrow}>TODAY&apos;S VIBE</Text><Text style={styles.panelTitle}>I&apos;m in the mood for...</Text><View style={styles.options}>{vibes.map(v => { const active = selected === v.label; return <Pressable key={v.label} onPress={() => setSelected(v.label)} style={({ pressed, hovered }: any) => [styles.option, active && styles.optionActive, (pressed || hovered) && styles.optionHover]}><Text style={styles.icon}>{v.icon}</Text><View style={styles.optionCopy}><Text style={[styles.optionTitle, active && styles.optionTitleActive]}>{v.label}</Text><Text style={[styles.optionSub, active && styles.optionSubActive]}>{v.sub}</Text></View><View style={[styles.radio, active && styles.radioActive]}>{active && <View style={styles.radioDot} />}</View></Pressable>})}</View><Pressable style={({ hovered }: any) => [styles.find, hovered && styles.findHover]}><Text style={styles.findText}>FIND MY NEXT RUN</Text><Feather name="arrow-up-right" size={18} color={colors.white} /></Pressable><Text style={styles.fine}>Demo only — we&apos;ll make the recommendations smart later.</Text></View>
  </View></View>;
}
const styles = StyleSheet.create({
  section: { backgroundColor: colors.cream, paddingVertical: 110, overflow: 'hidden' }, inner: { alignSelf: 'center', maxWidth: 1160, width: '100%', paddingHorizontal: 28, flexDirection: 'row', gap: 100, alignItems: 'center' }, mobile: { flexDirection: 'column', gap: 55, paddingHorizontal: 20, alignItems: 'stretch' }, intro: { flex: 1 }, number: { backgroundColor: colors.orange, width: 45, height: 45, alignItems: 'center', justifyContent: 'center', borderRadius: 25, marginBottom: 30, transform: [{ rotate: '-7deg' }] }, numberText: { color: colors.deep, fontFamily: fonts.bold, fontSize: 12 }, arrow: { marginTop: 35, transform: [{ rotate: '-5deg' }] }, arrowText: { color: colors.orange, fontSize: 55 }, note: { color: colors.forest, fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.3, marginLeft: 80, marginTop: -22 }, panel: { flex: 1.1, backgroundColor: colors.forest, padding: 35, borderRadius: 6, transform: [{ rotate: '1deg' }], shadowColor: '#14342b', shadowOpacity: .2, shadowRadius: 20, shadowOffset: { width: 8, height: 14 } }, panelEyebrow: { color: colors.lime, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 2 }, panelTitle: { color: colors.white, fontFamily: fonts.display, fontSize: 27, marginTop: 8, marginBottom: 22 }, options: { gap: 9 }, option: { backgroundColor: '#214c42', borderColor: '#3d655b', borderWidth: 1, flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 4 }, optionActive: { backgroundColor: colors.lime, borderColor: colors.lime, transform: [{ translateX: -7 }, { rotate: '-.6deg' }] }, optionHover: { borderColor: colors.orange }, icon: { fontSize: 24, width: 40 }, optionCopy: { flex: 1 }, optionTitle: { color: colors.white, fontFamily: fonts.bold, fontSize: 14 }, optionTitleActive: { color: colors.deep }, optionSub: { color: '#a9c0b9', fontFamily: fonts.body, fontSize: 11, marginTop: 2 }, optionSubActive: { color: '#486057' }, radio: { width: 17, height: 17, borderRadius: 10, borderColor: '#779088', borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, radioActive: { borderColor: colors.deep }, radioDot: { backgroundColor: colors.deep, width: 8, height: 8, borderRadius: 5 }, find: { backgroundColor: colors.orange, paddingVertical: 16, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9, borderRadius: 3, marginTop: 20 }, findHover: { transform: [{ scale: 1.015 }] }, findText: { color: colors.white, fontFamily: fonts.bold, fontSize: 11, letterSpacing: 1.2 }, fine: { color: '#809a92', fontFamily: fonts.body, fontSize: 9, textAlign: 'center', marginTop: 10 },
});
